// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Release",
    url: "assets/book-1.jpg",
    originalPrice: 29.99,
    salePrice: null,
    rating: 4,
  },
  {
    id: 2,
    title: "Forgotten Magic",
    url: "assets/book-2.jpg",
    originalPrice: 24.99,
    salePrice: 19.99,
    rating: 4.5,
  },
  {
    id: 3,
    title: "Sorry For Your Loss",
    url: "assets/book-3.jpg",
    originalPrice: 29.99,
    salePrice: 14.99,
    rating: 3.5,
  },
  {
    id: 4,
    title: "Infinity Reaper",
    url: "assets/book-4.jpg",
    originalPrice: 34.99,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 5,
    title: "Green Angels",
    url: "assets/book-5.jpg",
    originalPrice: 24.99,
    salePrice: 19.99,
    rating: 5,
  },
  {
    id: 6,
    title: "Middle School: Get Me Out of Here!",
    url: "assets/book-6.jpg",
    originalPrice: 14.99,
    salePrice: 9.99,
    rating: 4,
  },
  {
    id: 7,
    title: "Deep Tides",
    url: "assets/book-7.jpg",
    originalPrice: 14.99,
    salePrice: 9.99,
    rating: 4.5,
  },
  {
    id: 8,
    title: "Throne of Glass",
    url: "assets/book-8.png",
    originalPrice: 39.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 9,
    title: "Assassin's Creed: Forsaken",
    url: "assets/book-9.jpg",
    originalPrice: 39.99,
    salePrice: 29.99,
    rating: 3.5,
  },
  {
    id: 10,
    title: "Assassin's Creed: The Secret Crusade",
    url: "assets/book-10.jpg",
    originalPrice: 39.99,
    salePrice: 29.99,
    rating: 4.5,
  },
  {
    id: 11,
    title: "Assassin's Creed: Brotherhood",
    url: "assets/book-11.jpg",
    originalPrice: 39.99,
    salePrice: 29.99,
    rating: 5,
  },
  {
    id: 12,
    title: "Auring's Wrath",
    url: "assets/book-12.jpg",
    originalPrice: 24.99,
    salePrice: null,
    rating: 4.5,
  },
]