// FAKE DATA
export const books = [
  {
    id: 1,
    title: "It Ends With Us",
    url: "https://covers.openlibrary.org/b/id/12916653-L.jpg",
    originalPrice: 29.99,
    salePrice: null,
    rating: 4,
  },
  {
    id: 2,
    title: "Harry Potter and the Philosopher's Stone",
    url: "https://covers.openlibrary.org/b/id/10521270-L.jpg",
    originalPrice: 24.99,
    salePrice: 19.95,
    rating: 4.5,
  },
  {
    id: 3,
    title: "Sorry For Your Loss",
    url: "https://covers.openlibrary.org/b/id/8737159-L.jpg",
    originalPrice: 29.99,
    salePrice: 14.95,
    rating: 3.5,
  },
  {
    id: 4,
    title: "Infinity Reaper",
    url: "https://covers.openlibrary.org/b/id/10921235-L.jpg",
    originalPrice: 34.99,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 5,
    title: "Diary of a Wimpy KLid: Special CHEESIEST Edition",
    url: "https://covers.openlibrary.org/b/id/12474088-L.jpg",
    originalPrice: 24.99,
    salePrice: 19.95,
    rating: 5,
  },
  {
    id: 6,
    title: "Middle School: Get Me Out of Here!",
    url: "https://covers.openlibrary.org/b/id/8128391-L.jpg",
    originalPrice: 14.99,
    salePrice: 9.95,
    rating: 4,
  },
  {
    id: 7,
    title: "Ugly Love",
    url: "https://covers.openlibrary.org/b/id/13008803-L.jpg",
    originalPrice: 14.99,
    salePrice: 9.95,
    rating: 4.5,
  },
  {
    id: 8,
    title: "Throne of Glass",
    url: "https://covers.openlibrary.org/b/id/7268940-L.jpg",
    originalPrice: 39.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 9,
    title: "Assassin's Creed: Forsaken",
    url: "https://covers.openlibrary.org/b/id/8743129-L.jpg",
    originalPrice: 39.99,
    salePrice: 29.95,
    rating: 3.5,
  },
  {
    id: 10,
    title: "Assassin's Creed: The Secret Crusade",
    url: "https://covers.openlibrary.org/b/id/10296014-L.jpg",
    originalPrice: 39.99,
    salePrice: 29.95,
    rating: 4.5,
  },
  {
    id: 11,
    title: "Assassin's Creed: Brotherhood",
    url: "https://covers.openlibrary.org/b/id/6671385-L.jpg",
    originalPrice: 39.99,
    salePrice: 29.95,
    rating: 5,
  },
  {
    id: 12,
    title: "Atomic Habits",
    url: "https://covers.openlibrary.org/b/id/12886417-L.jpg",
    originalPrice: 19.99,
    salePrice: 17.95,
    rating: 3.5,
  },
  {
    id: 13,
    title: "The Subtle Art of Not Giving a F***",
    url: "https://covers.openlibrary.org/b/id/12833562-L.jpg",
    originalPrice: 29.99,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 14,
    title: "Full Dark, No Stars",
    url: "https://covers.openlibrary.org/b/id/10706103-L.jpg",
    originalPrice: 29.99,
    salePrice: 19.95,
    rating: 4,
  },
  {
    id: 15,
    title: "Sweet Addiction",
    url: "https://covers.openlibrary.org/w/id/7246876-M.jpg",
    originalPrice: 24.99,
    salePrice: 19.95,
    rating: 4,
  },
  {
    id: 16,
    title: "IT",
    url: "https://covers.openlibrary.org/b/id/12670684-L.jpg",
    originalPrice: 34.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 17,
    title: "The 48 Laws of Power",
    url: "https://covers.openlibrary.org/b/id/12920669-L.jpg",
    originalPrice: 25.99,
    salePrice: 22.95,
    rating: 3.5,
  },
  {
    id: 18,
    title: "Rich Dad, Poor Dad",
    url: "https://covers.openlibrary.org/b/id/12882777-L.jpg",
    originalPrice: 19.99,
    salePrice: 9.95,
    rating: 3.5,
  },
  {
    id: 19,
    title: "The Love Hypothesis",
    url: "https://covers.openlibrary.org/b/id/12842027-L.jpg",
    originalPrice: 19.99,
    salePrice: null,
    rating: 4,
  },
  {
    id: 20,
    title: "Verity",
    url: "https://covers.openlibrary.org/b/id/12924621-L.jpg",
    originalPrice: 34.99,
    salePrice: 23.95,
    rating: 5,
  },
  {
    id: 21,
    title: "Shatter Me",
    url: "https://covers.openlibrary.org/b/id/12726999-L.jpg",
    originalPrice: 24.99,
    salePrice: 19.95,
    rating: 5,
  },
  {
    id: 22,
    title: "Twisted: Love",
    url: "https://covers.openlibrary.org/b/id/12940491-L.jpg",
    originalPrice: 14.99,
    salePrice: null,
    rating: 4,
  },
  {
    id: 23,
    title: "The Summer I Turned Pretty",
    url: "https://covers.openlibrary.org/b/id/10362827-L.jpg",
    originalPrice: 24.99,
    salePrice: null,
    rating: 4,
  },
  {
    id: 24,
    title: "Haunting Adeline",
    url: "https://covers.openlibrary.org/b/id/12992962-L.jpg",
    originalPrice: 15.99,
    salePrice: 11.95,
    rating: 3,
  },
  {
    id: 25,
    title: "The Hunger Games",
    url: "https://covers.openlibrary.org/b/id/12646544-L.jpg",
    originalPrice: 39.99,
    salePrice: 35.95,
    rating: 5,
  },
  {
    id: 26,
    title: "The Silent Patient",
    url: "https://covers.openlibrary.org/b/id/9407338-L.jpg",
    originalPrice: 31.99,
    salePrice: 23.95,
    rating: 4,
  },
  {
    id: 27,
    title: "Twisted: Hate",
    url: "https://covers.openlibrary.org/b/id/12928487-L.jpg",
    originalPrice: 14.99,
    salePrice: null,
    rating: 4,
  },
  {
    id: 28,
    title: "Confess",
    url: "https://covers.openlibrary.org/b/id/12670028-L.jpg",
    originalPrice: 39.99,
    salePrice: null,
    rating: 4,
  },
  {
    id: 29,
    title: "Twisted: Games",
    url: "https://covers.openlibrary.org/b/id/12821465-L.jpg",
    originalPrice: 14.99,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 30,
    title: "Twisted: Lies",
    url: "https://covers.openlibrary.org/b/id/12816871-L.jpg",
    originalPrice: 14.99,
    salePrice: null,
    rating: 4.5,
  },
]